include:
  - board: nice_nano_v2
    shield: charrys_left
    artifact-name: charrys_left
    extra_configs:
      - /shields/charrys/charybdis_left.conf

  - board: nice_nano_v2
    shield: charrys_right
    artifact-name: charrys_right
    extra_configs:
      - /shields/charrys/charybdis_right.conf